feat: add form deletion
nditech/dev-elections pull request #602
Opened 2019-10-25 14:34 UTC by dodumosu

this PR adds the ability to delete forms.

see #569

2019-11-04 03:01 UTC, takinbo requested changes

2019-11-04 03:01 UTC, takinbo commented on apollo/formsframework/views_forms.py
> +@route(bp, '/delete', methods=['POST'])
@dodumosu all routes are now being handled within `views_admin.py`. Maybe you could use the same format for all the other views there?

2019-11-04 13:07 UTC, takinbo commented
PR works most of the time but occasionally, this happens:

![screenshot-1572872817](https://user-images.githubusercontent.com/41004/68123154-15ab2300-ff04-11e9-8b13-df256be928a5.png)

2019-11-04 13:08 UTC, takinbo requested changes
PR needs some bug fixing to be merged.

2020-05-25 16:03 UTC, takinbo requested changes

2020-05-25 16:03 UTC, takinbo commented on apollo/templates/admin/form_list.html
> +    var result = confirm("{{ _('Are you sure you want to delete this form? All submissions for it will be deleted too!') }}");
Can we rephrase to `"All data linked to this form will be deleted too."`?

2021-02-09 21:19 UTC, takinbo requested changes
I'm still unable to delete forms. See this [video](https://youtu.be/MPCclS4HJuM) for a demonstration.

2021-02-09 21:38 UTC, dodumosu commented
was the worker process running when you used it? the actual deletion is done in a worker thread, because it deletes all submissions first.

2021-02-10 07:20 UTC, takinbo commented
> was the worker process running when you used it? the actual deletion is done in a worker thread, because it deletes all submissions first.

Yes the worker thread was running and there were no submissions.

2021-02-10 08:02 UTC, dodumosu commented
that's definitely weird, because i tried it out and didn't have any issues: https://vimeo.com/510580040

2022-04-19 08:53 UTC, closed without merging