fix: various fixes
nditech/dev-elections pull request #738
Opened 2020-09-18 00:02 UTC by dodumosu

this pull request attempts to address:

- nditech/apollo-issues#89, where the "recent phone" was inaccurate
- nditech/apollo-issues#90, where the "db phone" and "recent phone" were to be updated
- nditech/apollo-issues#91, where a specific order for participant phone numbers was to be set
- nditech/apollo-issues#92, where the "db phone" and "recent phone" for location submission export was to match the observer export

2020-09-22 17:56 UTC, takinbo requested changes

2020-09-22 17:56 UTC, takinbo commented on apollo/submissions/services.py
> +                    submission.last_phone_number,
We should store safe values if the submission does not have a value for `last_phone_number`.

2020-09-22 17:56 UTC, takinbo commented on apollo/submissions/services.py
> +                    sib.last_phone_number,
Set a safe value in case a value for `last_phone_number` is not available.

2020-09-22 17:59 UTC, dodumosu commented on apollo/submissions/services.py
> +                    submission.last_phone_number,
the property defaults to ```None```, which is output as an empty string

2020-09-23 16:45 UTC, takinbo approved these changes
utACK

2020-09-23 16:46 UTC, merged