Allow uploads of images via ODK
nditech/dev-elections pull request #766
Opened 2020-11-08 15:55 UTC by dodumosu

this pull request allows Apollo manage participant-submitted images via ODK as responses to questions. it also allows for the configuration of ODK Collect via a QR Code, either for the entire system (in which case no credentials are applied), or for a specific participant.
Image uploads can be configured locally or for Amazon S3. Relevant settings are:
- `ATTACHMENTS_USE_S3` (boolean flag, set to true if uploads should go to S3)
- `AWS_ACCESS_KEY_ID`: required if the above is true
- `AWS_SECRET_ACCESS_KEY`: required if the above is true
- `AWS_DEFAULT_REGION`: optional
- `AWS_DEFAULT_BUCKET`: optional
- `AWS_IMAGES_REGION`: specifically for images. defaults to `AWS_DEFAULT_REGION`
- `AWS_IMAGES_BUCKET`: specifically for images: defaults to `AWS_DEFAULT_BUCKET`
- `AWS_ENDPOINT_URL`
- `DEFAULT_STORAGE_PATH`: defaults to the configured path for uploads
- `IMAGES_STORAGE_PATH`: defaults to a subfolder named `images` in `DEFAULT_STORAGE_PATH`

2020-11-10 04:35 UTC, takinbo commented
@dodumosu rebase

2020-11-10 07:21 UTC, dodumosu commented
rebased

2020-12-07 03:15 UTC, takinbo requested changes

2020-12-07 03:15 UTC, takinbo commented on apollo/formsframework/forms.py
> +    allow_attachments = wtforms.BooleanField(
This will not be necessary since we can already add the image field using the form builder

2020-12-07 03:15 UTC, takinbo commented on apollo/formsframework/models.py
> +    ALL_FIELD_TYPES = FIELD_TYPES
Why do we need `ALL_FIELD_TYPES` when we have `FIELD_TYPES`?

2020-12-07 03:15 UTC, takinbo commented on apollo/formsframework/models.py
> +                        mediatype = f'{field_type}/*'
maybe this should just be `'image/*'`?

2020-12-07 03:15 UTC, takinbo commented on apollo/formsframework/models.py
> -
What happened to this functionality?

2020-12-07 03:15 UTC, takinbo commented on apollo/formsframework/utils.py
> +            field['type'] = record_type
Isn't this a weird syntax? If `record_type` is `'image'`, then why not just simply set `field['type']` to `'image'`?

2020-12-07 03:15 UTC, takinbo commented on apollo/odk/utils.py
> +    return img_buffer.getvalue()
Can you split this functionality into a separate PR?

2020-12-07 03:15 UTC, takinbo commented on apollo/odk/views_odk.py
> -from apollo.odk.utils import make_message_text
Is there another method called `make_message_text`?

2020-12-07 03:15 UTC, takinbo commented on apollo/odk/views_odk.py
> +    return response
Separate PR

2020-12-07 03:15 UTC, takinbo commented on apollo/settings.py
> +    config('DEFAULT_STORAGE_PATH', default=default_upload_path))
where is it getting `default_upload_path` from?

2020-12-07 03:15 UTC, takinbo commented on apollo/settings.py
> +AWS_IMAGES_BUCKET = config('AWS_IMAGES_BUCKET', default=AWS_DEFAULT_BUCKET)
why do we need both `AWS_DEFAULT_REGION` and `AWS_IMAGES_REGION`?

2020-12-07 03:15 UTC, takinbo commented on apollo/settings.py
> +AWS_ENDPOINT_URL = config('AWS_ENDPOINT_URL', default=None)
Shouldn't there be a sensible default?

2020-12-07 03:15 UTC, takinbo commented on apollo/settings.py
> +AWS_DEFAULT_BUCKET = config('AWS_DEFAULT_BUCKET', default=None)
Sensible defaults

2020-12-07 03:15 UTC, takinbo commented on apollo/static/js/angular-form-builder-components.js
> +
I am not certain we agreed to have location as a form builder component. We don't have a use case where an observer gets to report more than one location per submission.

2020-12-07 04:43 UTC, dodumosu commented on apollo/settings.py
> +AWS_IMAGES_BUCKET = config('AWS_IMAGES_BUCKET', default=AWS_DEFAULT_BUCKET)
since ODK supports the following media types: image, audio, video, other, depending on whoever is deploying, they might want to have different media in different buckets and/or regions.

2020-12-07 04:44 UTC, dodumosu commented on apollo/settings.py
> +AWS_ENDPOINT_URL = config('AWS_ENDPOINT_URL', default=None)
they all default to `None`

2020-12-07 04:50 UTC, dodumosu commented on apollo/settings.py
> +AWS_DEFAULT_BUCKET = config('AWS_DEFAULT_BUCKET', default=None)
as mentioned above, they default to `None`. it's all set up so that if, for example, it makes sense to fine tune a set up and tweak more of the S3 configuration (for example, using a geographically closer region for faster media loading), it is possible to do that without needing to bend over backwards or add new code. if you don't need that level of configuration, you can ignore it.

2020-12-07 04:51 UTC, dodumosu commented on apollo/static/js/angular-form-builder-components.js
> +
i believe we have earlier had a conversation around using locations in QA, the same way we often ask similar questions twice.

2020-12-07 04:54 UTC, dodumosu commented on apollo/formsframework/models.py
> -
instead of hard coding a location question into the generated XForm (where it would always be present even if the location wasn't actually required or used) at the end, you would now add a location question using the form builder.

2020-12-07 05:11 UTC, dodumosu commented on apollo/settings.py
> +    config('DEFAULT_STORAGE_PATH', default=default_upload_path))
it's defined on L181

2020-12-08 02:43 UTC, takinbo commented on apollo/formsframework/models.py
> -
![Screenshot from 2020-12-08 02-41-57](https://user-images.githubusercontent.com/41004/101431533-01073e80-38ff-11eb-8e92-48ad3540ed61.png)

The UI is designed with the idea that we would not have more than one location data per submission so I don't think we would be making location something that can be arbitrarily defined.

2020-12-08 02:44 UTC, takinbo commented on apollo/settings.py
> +AWS_ENDPOINT_URL = config('AWS_ENDPOINT_URL', default=None)
If they default to `None`, why have defaults in the first place?

2020-12-08 02:45 UTC, takinbo commented on apollo/settings.py
> +AWS_IMAGES_BUCKET = config('AWS_IMAGES_BUCKET', default=AWS_DEFAULT_BUCKET)
Ok.

2020-12-08 02:46 UTC, takinbo commented on apollo/settings.py
> +AWS_DEFAULT_BUCKET = config('AWS_DEFAULT_BUCKET', default=None)
If this value is left as `None`, what does the library use as the default region?

2020-12-08 02:48 UTC, takinbo commented on apollo/static/js/angular-form-builder-components.js
> +
I don't think it makes sense. Location data is not something you can make a mistake about and I'm not sure it was something I would have agreed to. We have UI that expects to read location data from a known field. This change will affect that and I don't see the value add.

2020-12-20 06:45 UTC, takinbo requested changes
Comments inline. Also this PR needs a rebase.

2020-12-20 06:45 UTC, takinbo commented on apollo/formsframework/models.py
> +    'comment', 'integer', 'select', 'multiselect', 'string', 'location',
We don't need a `location` field type and I don't believe we are even using one. We are currently using the `geom` attribute in the submission model for this.

2021-01-06 06:58 UTC, takinbo requested changes
I'm getting this error when I try to spin a container:

```
worker_1    | Traceback (most recent call last):
worker_1    |   File "/app/manage.py", line 15, in <module>
worker_1    |     from apollo.core import db
worker_1    |   File "/app/apollo/__init__.py", line 15, in <module>
worker_1    |     from apollo import assets, models, services
worker_1    |   File "/app/apollo/models.py", line 14, in <module>
worker_1    |     from apollo.submissions.models import (  # noqa
worker_1    |   File "/app/apollo/submissions/models.py", line 3, in <module>
worker_1    |     from depot.fields.specialized.image import UploadedImageWithThumb
worker_1    |   File "/usr/local/lib/python3.6/site-packages/depot/fields/specialized/image.py", line 5, in <module>
worker_1    |     from PIL import Image
worker_1    | ModuleNotFoundError: No module named 'PIL'
```

2021-01-09 20:46 UTC, takinbo approved these changes
tACK

2021-01-09 20:49 UTC, merged