quality assurance updates
nditech/dev-elections pull request #772
Opened 2020-11-12 12:25 UTC by dodumosu

this PR contains the following changes to how Apollo works:
- invalid QA for any reason (badly formed expressions, multiple choice fields used, invalid question codes used) will always evaluate to `Missing`
- the user entering QA is prompted with a message when there is an issue with entered QA, _even though it is saved_

![Screenshot_2020-11-12 Forms - Apollo(3)](https://user-images.githubusercontent.com/1408662/98939885-6d527600-24ea-11eb-9ca2-571b569c7225.png)
![Screenshot_2020-11-12 Forms - Apollo(4)](https://user-images.githubusercontent.com/1408662/98939889-6e83a300-24ea-11eb-9f6f-b1328d9ee31d.png)

2020-12-07 03:19 UTC, takinbo requested changes
This PR should be simplified. Rather than display a modal with an error, we should rather not return any question codes that are multiple choice, image, location or comment fields. If a QA expression for some reason contains any of these, then it should return the `no data` state and not attempt to compute the QA status.

2020-12-08 02:36 UTC, takinbo requested changes

2020-12-08 02:36 UTC, takinbo commented on apollo/templates/admin/quality_assurance_error_fragment.html
> +</ul>
Do we need this?

2020-12-08 02:36 UTC, takinbo commented on apollo/formsframework/views_forms.py
> +                return jsonify(data), status_code
do we still need this considering we aren't displaying any errors again?

2020-12-08 02:36 UTC, takinbo commented on apollo/templates/admin/quality_assurance.html
> +{% endwith %}
I suspect this is not needed?

2020-12-08 02:36 UTC, takinbo commented on apollo/templates/admin/quality_assurance_edit.html
> +</div>
I suspect this is not needed?

2020-12-08 03:09 UTC, takinbo requested changes

2020-12-08 03:09 UTC, takinbo commented on apollo/submissions/qa/messages.py
> +}
In light of our removal of the dialog for display of errors, shouldn't we be redefining this as well?

2020-12-08 13:47 UTC, takinbo requested changes

2020-12-08 13:47 UTC, takinbo commented on apollo/formsframework/views_forms.py
> +
This will probably also need clean up considering we're not using those errors anymore?

2020-12-08 13:47 UTC, takinbo commented on apollo/submissions/qa/messages.py
> +    MULTISELECT_VARIABLE = 4
If we're not returning any errors in the QA builder, do we still need this?

2020-12-13 00:48 UTC, takinbo requested changes
A few extraneous unused lines and this PR should be good for merging

2020-12-13 00:48 UTC, takinbo commented on apollo/submissions/qa/query_builder.py
> +            self.invalid_variables.add(var_name)
Is there a current usecase for these?

2020-12-13 00:48 UTC, takinbo commented on apollo/submissions/qa/query_builder.py
> +            self.multiple_choice_variables.add(var_name)
Same.

2020-12-13 00:48 UTC, takinbo commented on apollo/submissions/qa/query_builder.py
> +            self.invalid_variables.add(var_name)
Same.

2020-12-13 00:48 UTC, takinbo commented on apollo/submissions/qa/query_builder.py
> +            self.multiple_choice_variables.add(var_name)
Same.

2020-12-15 21:47 UTC, takinbo requested changes
Could you please test this and confirm it's working? I applied the PR to a working system and all the questions are no longer visible in the QA builder.

2020-12-16 05:43 UTC, dodumosu commented
i'm unable to replicate the issue you have had. perhaps you could send a dump of your database?

![firefox_vxpJAEzwTe](https://user-images.githubusercontent.com/1408662/102309821-f6d1e980-3f69-11eb-8a86-eb9f5dba47db.png)
![firefox_mn1759ZcCT](https://user-images.githubusercontent.com/1408662/102309827-fb969d80-3f69-11eb-921c-c44651838f22.png)
![firefox_cm0K9qMnrL](https://user-images.githubusercontent.com/1408662/102309842-04876f00-3f6a-11eb-9516-88aff4b0ad00.png)
![C3Qw7xojxz](https://user-images.githubusercontent.com/1408662/102309849-08b38c80-3f6a-11eb-9050-5685996296bf.png)

2020-12-20 06:38 UTC, takinbo approved these changes
tACK

2020-12-20 06:39 UTC, merged