Turnerd patch 1
nditech/dev-elections pull request #781
Opened 2021-01-10 16:25 UTC by turnerd

Revisions to readme with docker-compose

2021-01-10 20:11 UTC, takinbo requested changes

2021-01-10 20:11 UTC, takinbo commented on README.md
> +    server_name apollodemo.demcloud.org;
Since we're still using `INSERT_SITE_URL` as the placeholder, I suggest we keep that instead of using an actual value like `apollodemo.demcloud.org`

2021-01-10 20:11 UTC, takinbo commented on README.md
> +You should now be able to log in to your site by navigating to the IP or URL for your server, or if you are running it locally without nginx by going to port 5000 on your localhost (http://localhost:
Can we change the wording to make it a hard suggestion to change the password on the first login? So we should use language like "This should be changed upon logging in."

2021-01-13 19:11 UTC, turnerd commented on README.md
> +    server_name apollodemo.demcloud.org;
good catch!

2021-01-13 19:15 UTC, turnerd commented on README.md
> +You should now be able to log in to your site by navigating to the IP or URL for your server, or if you are running it locally without nginx by going to port 5000 on your localhost (http://localhost:
Good idea

2021-01-13 19:19 UTC, takinbo approved these changes
LGTM

2021-01-13 19:24 UTC, merged