prevent saving form if duplicate questions or section headers are used in builder
nditech/dev-elections pull request #826
Opened 2021-08-06 10:52 UTC by dodumosu

see: nditech/apollo-issues#15

2021-08-17 05:30 UTC, takinbo requested changes
Functionality works but notification system doesn't match the UX of the frontend framework. We should use a modal here:
![Screenshot from 2021-08-17 05-28-27](https://user-images.githubusercontent.com/41004/129668766-b4746460-94ed-48ec-8511-020bd70f80f8.png)

2021-08-17 07:05 UTC, dodumosu commented
![firefox_deCbV7eznH](https://user-images.githubusercontent.com/1408662/129679471-62b425b4-0b0d-474f-b294-74c0a417cf32.png)
would this be sufficient?

2021-08-17 15:44 UTC, takinbo commented
> would this be sufficient?

Unfortunately not.

Why are we not using [Toasts](https://getbootstrap.com/docs/4.6/components/toasts/)?

There are three solutions I can suggest:

1. Toasts (Bootstrap)
2. Alerts (Bootstrap)
3. A simple modal dialog with a close button

2021-08-20 17:46 UTC, takinbo commented
We're almost there. Can you split this into two message alerts. One for the sections and another for the question codes. I've made prototypes:

![Screenshot from 2021-08-20 17-44-25](https://user-images.githubusercontent.com/41004/130273278-af7a02e5-b4c1-40cd-9c81-e79412ca1361.png)

![Screenshot from 2021-08-20 17-42-19](https://user-images.githubusercontent.com/41004/130273282-7d25c19b-6678-4ea9-9fcf-c6a6a60c4878.png)

2021-08-20 17:46 UTC, takinbo requested changes
See general comments

2021-08-20 17:47 UTC, takinbo commented
Also, when you're done, please squash your commits into one.

2021-09-06 15:34 UTC, takinbo requested changes

2021-09-06 15:34 UTC, takinbo commented on apollo/templates/admin/formbuilder.html
> +<link rel="stylesheet" href="{{ url_for('pwa.static', filename='vendor/notiflix/notiflix-2.7.0.min.css') }}">
Not necessary since it's not being used.

2021-09-06 15:34 UTC, takinbo commented on apollo/templates/admin/formbuilder.html
> +<script src="{{ url_for('pwa.static', filename='vendor/notiflix/notiflix-2.7.0.min.js') }}"></script>
Should be removed since it's not being used

2021-09-06 18:39 UTC, takinbo approved these changes
tACK

2021-09-06 18:40 UTC, merged