fix: use a subquery to filter by participant role
nditech/dev-elections pull request #863
Opened 2021-12-12 04:45 UTC by dodumosu

when viewing a list of submissions and it gets filtered by a
participant role, the filter works, but errors out when one exports.
This commit fixes that by using an explicit subquery,
and does not assume that the participant role table is joined to the
main query (which is the case when exporting).

see: nditech/apollo-issues#166

2021-12-13 17:58 UTC, takinbo commented on apollo/submissions/filters.py
> +                    models.Submission.participant_id.in_(subquery))
I'm concerned about the performance of `in_` queries in general. Is there a way to make a reference to the `Participant` model through the relationship on the `Submission` model and do the filtering on the `Participant` model?

2022-02-18 06:54 UTC, takinbo commented
My concern is the performance cost of doing things this way. If when viewing the submissions, a participant is included, why aren't we doing the same for the exports? Maybe it might be better to do a join against the Participants model when doing an export?

2022-02-18 06:54 UTC, takinbo requested changes
See comments for recommendations

2022-02-18 08:46 UTC, dodumosu commented
the code checks if there's a join on the `Participant` model and creates one if there isn't, then checks if there's a join on the `ParticipantRole`, and also creates a join if it doesn't exist (because it depends on the previous join). We reuse the filter in different contexts, and we do not always have the requisite joins we need to make the filter work, hence if the filter isn't used, the joins are never created.

as to why, when exporting the location/master or the aggregate checklists, there is no join on the `Participant` model. the only case where there is a join on the `Participant` model for an export is when there's an observer checklist export or a QA export.

2022-02-21 06:38 UTC, takinbo requested changes
Code could be more concise; I don't know if it would also reduce memory usage since it reuses labels

2022-02-21 06:38 UTC, takinbo commented on apollo/submissions/filters.py
> +                    query1 = query.join(models.Submission.participant)
Might be better to rewrite as:

```python
if models.Participant not in joined_classes:
    query = query.join(models.Submission.participant)
```

2022-02-21 06:38 UTC, takinbo commented on apollo/submissions/filters.py
> +                return query2.filter(models.ParticipantRole.id == value)
can be rewritten as:

```python
if models.ParticipantRole not in joined_classes:
    query = query.join(
        models.ParticipantRole,
        models.Participant.role_id == models.ParticipantRole.id
    )

return query.filter(models.ParticipantRole.id == value)
```

2022-02-27 01:40 UTC, takinbo approved these changes
LGTM

2022-02-27 01:40 UTC, merged

2022-02-27 01:52 UTC, takinbo commented
@dodumosu this PR broke exports and I only just tested it after merging which is why I reverted the commit. Can you resubmit and please test before creating the PR.

2022-02-27 01:53 UTC, takinbo commented
If it helps...

![Screenshot from 2022-02-27 01-53-07](https://user-images.githubusercontent.com/41004/155865101-4a43381b-024a-42b8-a946-d561199a0118.png)