feature: bulk user import
nditech/dev-elections pull request #866
Opened 2022-01-21 21:51 UTC by dodumosu

this feature addresses nditech/apollo-issues#167 and provides a way to create a large number of user accounts at once.

2022-12-06 05:12 UTC, takinbo requested changes

2022-12-06 05:12 UTC, takinbo commented on apollo/factory.py
> +
Is this necessary?

2022-12-06 06:17 UTC, dodumosu commented on apollo/factory.py
> +
not any longer, since asynchronous import was removed

2023-08-22 10:45 UTC, closed without merging

2023-08-22 10:46 UTC, dodumosu commented
closed in favour of nditech/apollo#949