feat: run event deletion in the worker
nditech/dev-elections pull request #867
Opened 2022-02-01 03:09 UTC by dodumosu

this PR addresses nditech/apollo-issues#168 by moving the deletion
out of the web process and into the worker process.
The deletion is done using SQLAlchemy Core, not the ORM.
Finally, a restriction against deleting an event in use by the
initiating admin user is put in place.

see: nditech/apollo-issues#168

2022-02-21 06:40 UTC, takinbo requested changes
If there's an exception during the process of executing the task, there doesn't seem to be a way to explicitly roll back the transaction and safely exit.

2022-02-21 07:00 UTC, dodumosu commented
according to the [SQLAlchemy documentation](https://docs.sqlalchemy.org/en/14/core/connections.html#using-transactions), if there's an exception during a transaction, the transaction gets rolled back. i have added explicit exception handling to the code though

2022-02-27 02:01 UTC, takinbo requested changes
Some rewording and suggestions

2022-02-27 02:01 UTC, takinbo commented on apollo/frontend/views_admin.py
> +                message = str(_('Cannot delete the current event'))
Can we reword to "You cannot delete the active event."

2022-02-27 02:01 UTC, takinbo commented on apollo/frontend/views_admin.py
> +            message = str(_("Selected event(s) marked for deletion"))
Reword to: "The selected event(s) are now scheduled for deletion."

How do we prevent admins from attempting to delete the event again? Instead of deleting events, can we just hide them and make them inaccessible? We might apply the same to other data objects in the database.

2022-02-27 04:13 UTC, dodumosu commented
Closing in order to consider the implications of making events inaccesible

2022-02-27 04:13 UTC, closed without merging