Add support for hiding/unhiding objects
nditech/dev-elections pull request #884
Opened 2022-04-26 11:21 UTC by dodumosu

This pull request addresses nditech/apollo-issues#171 by allowing a user to hide or show location sets, participant sets, events and forms.

2024-03-11 15:53 UTC, takinbo requested changes

2024-03-11 15:53 UTC, takinbo commented on migrations/versions/14d0310ab80f_add_is_hidden_field.py
> +    )
There's no point in making these columns nullable and they should have a default value of `False`

2024-03-11 15:53 UTC, takinbo commented on apollo/submissions/views_submissions.py
>      filter_class = filters.generate_quality_assurance_filter(g.event, form)
We should probably also have the same for the submissions list (Checklist, Surveys and Critical Incidents)

2024-03-11 15:53 UTC, takinbo commented on apollo/formsframework/fixtures/38fff911ea3.sql
> +INSERT INTO public.form VALUES (6, 'IN-3-1', false, 'WC', 'INCIDENT', true, true, NULL, '34d79b36acf74dd99bbf8b68631f587c', 9, NULL, NULL, NULL, NULL, false, NULL, NULL, NULL);
This presumes to know the order in which the columns were created. To remove the ambiguity, the column names should be specified before the values.

2024-03-11 15:53 UTC, takinbo commented on apollo/formsframework/views_forms.py
> +        show_toggle_link_label = _('Hide Hidden')
What does "Hide Hidden" mean? The language should probably be clearer than this.

2024-03-11 15:53 UTC, takinbo commented on apollo/formsframework/views_forms.py
> +            'Show All (%(count)d Hidden)', count=hidden_form_count)
Can you explain the rational for having the number of hidden objects displayed here?

2024-03-11 15:53 UTC, takinbo commented on apollo/frontend/views_admin.py
> +    @action('unhide', _('Always Show'), _('Are you sure you want to always show the selected items?'))
Instead of using `Hide` and `Always Show`, could we instead use `Archive` and `Unarchive`?

2024-03-11 15:53 UTC, takinbo commented on apollo/templates/admin/form_list.html
> +      <button class="btn btn-secondary mr-2 invisible" id="show_button">{{ _('Show Selected') }}</button>
`Archive` and `Unarchive`?

2024-04-23 12:48 UTC, dodumosu commented on apollo/frontend/views_admin.py
> +    @action('unhide', _('Always Show'), _('Are you sure you want to always show the selected items?'))
This has been changed

2024-04-23 12:49 UTC, dodumosu commented on apollo/templates/admin/form_list.html
> +      <button class="btn btn-secondary mr-2 invisible" id="show_button">{{ _('Show Selected') }}</button>
Changed to `Archive` and `Unarchive`, respectively

2024-04-23 12:50 UTC, dodumosu commented on apollo/formsframework/views_forms.py
> +            'Show All (%(count)d Hidden)', count=hidden_form_count)
It was to give the user the number of items that weren't being displayed, but it's been removed

2024-04-23 12:51 UTC, dodumosu commented on apollo/formsframework/views_forms.py
> +        show_toggle_link_label = _('Hide Hidden')
changed to `Hide Archived`

2024-04-23 12:53 UTC, dodumosu commented on migrations/versions/14d0310ab80f_add_is_hidden_field.py
> +    )
all set to `default=False` and `nullable=False` on the respective model classes

2024-05-01 13:12 UTC, takinbo commented
<img width="485" alt="Screenshot 2024-05-01 at 14 10 20" src="https://github.com/nditech/apollo/assets/41004/b2364bae-6c12-4465-a438-5d3ef5286e52">

@dodumosu can you update the migration so it's applied after `7cbcd7443117`? Given there are no conflicts of course.

2024-05-01 17:11 UTC, dodumosu commented
done

> <img alt="Screenshot 2024-05-01 at 14 10 20" width="485" src="https://private-user-images.githubusercontent.com/41004/327129153-b2364bae-6c12-4465-a438-5d3ef5286e52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1ODIzODcsIm5iZiI6MTcxNDU4MjA4NywicGF0aCI6Ii80MTAwNC8zMjcxMjkxNTMtYjIzNjRiYWUtNmMxMi00NDY1LWE0MzgtNWQzZWY1Mjg2ZTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDE2NDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYmVmZDZmZjE3YTYyMGM1Y2NlY2U3OWNiMmQ5ODU2NWY2MjE0OGYzMWIyZTQ5N2I1NzQ1NzUxZmI0ZGU4NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xQHB57tJs7_GYEHOndRXc3O1K41iwqrPRFCeyogAexs">
> @dodumosu can you update the migration so it's applied after `7cbcd7443117`? Given there are no conflicts of course.

done

2024-05-13 16:16 UTC, takinbo commented
Trying to edit any of the events (whether archived or not), yields this error:

<img width="911" alt="Screenshot 2024-05-13 at 17 15 01" src="https://github.com/nditech/apollo/assets/41004/6ac222ef-e91f-4490-a1ef-429fcc327794">

2024-05-14 03:52 UTC, takinbo commented
There are still issues with the PR:

1. Hiding/Unhiding events does not work - they are still being displayed and I have no way of knowing if the event was hidden
2. Hiding a participant set does not remove it from available options when creating an event
3. Hiding a location set does not remove it from available options when creating a participant set
4. There's no way to archive forms

<img width="1225" alt="Screenshot 2024-05-14 at 04 50 09" src="https://github.com/nditech/apollo/assets/41004/e11a6701-7635-4c01-ae74-9f946cc3778d">

2024-05-15 19:44 UTC, takinbo commented
Archive/Unarchive buttons do not show up when the "All Forms" checkbox is selected.

![Screenshot 2024-05-15 at 20 43 46](https://github.com/nditech/apollo/assets/41004/cf57c6fc-9a82-4fbd-8d09-d6b7337b9661)

2024-05-15 19:47 UTC, dodumosu commented
They remain hidden until one or more check boxes are selected. Should I
change that behaviour?

On Wed, 15 May 2024, 20:44 Tim Akinbo, ***@***.***> wrote:

> Archive/Unarchive buttons do not show up when the "All Forms" checkbox is
> selected.
>
> Screenshot.2024-05-15.at.20.43.46.png (view on web)
> <https://github.com/nditech/apollo/assets/41004/cf57c6fc-9a82-4fbd-8d09-d6b7337b9661>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nditech/apollo/pull/884#issuecomment-2113333524>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKX5FXAVAJJGXPIZNFUE63ZCO3LDAVCNFSM5ULQG2NKU5DIOJSWCZC7NNSXTN2JONZXKZKDN5WW2ZLOOQ5TEMJRGMZTGMZVGI2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-15 19:57 UTC, takinbo commented
After archiving Events, the archived events are still selectable from the Events selection menu dropdown

![Screenshot 2024-05-15 at 20 56 49](https://github.com/nditech/apollo/assets/41004/bcabf790-a44f-43b0-89e7-f0444fa712b1)

2024-07-24 21:41 UTC, takinbo approved these changes
tACK

2024-07-24 21:42 UTC, merged