Add participant languages
nditech/dev-elections pull request #887
Opened 2022-07-22 17:07 UTC by dodumosu

This PR adds support for responding to text messages in a preset language for a participant (see nditech/apollo-issues#176).

In order to set this up:
- the deployment primary and other languages must be set up in the admin;
- individual participant languages should be set by importing in the specified column a two-letter language code that matches one of the supported languages, OR
- edit a participant and set the language in the edit participant screen

Participants that have no language set default to the default language for the deployment, and the same occurs for messages that cannot load a valid participant.
![ifNYgQSFGt](https://user-images.githubusercontent.com/1408662/180489045-09df1b6e-f4aa-4f04-bceb-d3d5884876cb.png)

![eM0Z5LX1ai](https://user-images.githubusercontent.com/1408662/180489488-e539d348-4e11-4658-baa0-b87a8b1d3a6a.png)

In the screenshots above participant 2001 has their language set to French, 2002 has theirs set to English, and 2003 has no language set

2022-07-22 17:09 UTC, dodumosu commented
The PR is this large because the language catalogs have been rebuilt.

2022-07-26 15:43 UTC, takinbo commented
Is the catalog containing any new translation strings? If not, I would suggest reviewing the PR and excluding any files that didn't undergo any meaningful change. I'll preview to review a smaller PR.

2022-07-26 17:07 UTC, dodumosu commented
It doesn't contain updated strings, but the number of lines in the source code have changed, and the translations won't work without being rebuilt. I can remove the commit that changes the translations, but you will need to rebuild them locally to test, for example.

2022-07-27 00:54 UTC, takinbo requested changes
I'll like to see unit tests written for this feature.

2022-07-27 00:54 UTC, takinbo commented on apollo/participants/models.py
> +            'locale': _('Language code'),
Can we name this simply Language or we call it Locale?

2022-07-27 00:54 UTC, takinbo commented on apollo/frontend/forms.py
> +        _('Language'),
"Locale"

2022-07-27 00:54 UTC, takinbo commented on apollo/messaging/helpers.py
> +    if prefix and participant_id and responses:
We need to come up with a consistent code writing style and stick to it. It should overtime lead to less and less code rewrites like this. This is essentially a cosmetic change.

2022-07-27 05:39 UTC, dodumosu commented on apollo/messaging/helpers.py
> +    if prefix and participant_id and responses:
we could choose a formatter and rules and use that?

2022-12-06 05:06 UTC, takinbo commented on apollo/__init__.py
> +        monitor(app)
Is this still an issue?

2022-12-06 05:11 UTC, takinbo commented on apollo/testutils/factory.py
> +    return app
I don't understand the need for this. These variables are configured automatically in the test environment why create another method for this?

2022-12-06 06:10 UTC, dodumosu commented on apollo/testutils/factory.py
> +    return app
it's not for the variables, though. this is related to your comment on nditech/apollo#866. the app created using `create_app()` from `apollo/factory.py` doesn't have flask-security set up, while `create_app()` from `apollo/__init__.py` does have flask-security set up properly using the user datastore.

2022-12-06 06:14 UTC, dodumosu commented on apollo/testutils/factory.py
> +    return app
![WindowsTerminal_8Mp3WUtkJs](https://user-images.githubusercontent.com/1408662/205835507-d7d0b090-52f3-41d5-ae54-6d04896a46d5.png)
An example of what happens when `create_app()` from `apollo/factory.py` is used instead of from the package module, because flask-security wasn't set up

2022-12-06 11:50 UTC, dodumosu commented on apollo/__init__.py
> +        monitor(app)
since we've changed from using nose to pytest, no

2023-12-19 16:05 UTC, takinbo requested changes

2023-12-19 16:05 UTC, takinbo commented on apollo/testutils/factory.py
> +    return app
Do we still need this?

2023-12-20 17:15 UTC, takinbo requested changes
Change the user-facing language for "Locale" to "Preferred Language"

2023-12-20 17:15 UTC, takinbo commented on apollo/frontend/forms.py
> +        choices=_make_choices(languages.items(), _('Unspecified')))
It could be a little confusing for users to use the term "Locale" in referring to the preferred language. On the backend, we can use locale but we should use "Preferred Language" on the user-facing side.

2024-03-05 21:38 UTC, takinbo requested changes
Besides the individual comments, I noticed that responses are returned in the configured locale if the text message is valid (even if the responses are not); for invalid messages, would it be possible to attempt a lookup of the phone number to identify the user? This might offer a better user experience. If the observer can be identified by the id in the text message, fine if not, attempt the identification based on the sender.

2024-03-05 21:38 UTC, takinbo commented on apollo/participants/models.py
> +            'locale': _('Locale'),
Let's use `_('Preferred Language')` instead.

2024-03-05 21:38 UTC, takinbo commented on apollo/frontend/forms.py
> +        choices=_make_choices(languages.items(), _('Unspecified')))
Instead of using `Unspecified` let's change it to `Default` so it's not confused as to whether it has to be specified.

2024-03-11 15:34 UTC, takinbo approved these changes
utACK

2024-03-11 15:35 UTC, merged