Add image columns to tables
nditech/dev-elections pull request #897
Opened 2022-09-12 16:55 UTC by dodumosu

Adds one to two extra columns to submission (checklist/incident/survey) tabular views, depending on if images fields are defined for the form in the form builder:
- one column if any image field is defined. this column simply indicates the absence/presence of any image data whatsoever, independent of which field(s)
- two columns if any of the image fields is defined as a result image field. this column contains the number of results images uploaded

see nditech/apollo-issues#184. this pull request supercedes #895

2022-09-13 21:17 UTC, takinbo requested changes

2022-09-13 21:17 UTC, takinbo commented on apollo/frontend/templates/frontend/macros/submission_list_macros.html
> +    {%- set colspan = cspan + (location_types|length) + form_fields|length + (1 if form.has_image_fields else 0) -%}
Aren't we also going to factor in `form.result_images`?

2022-09-14 08:41 UTC, dodumosu commented on apollo/frontend/templates/frontend/macros/submission_list_macros.html
> +    {%- set colspan = cspan + (location_types|length) + form_fields|length + (1 if form.has_image_fields else 0) -%}
that line applies only when the form is an incident form, as can be seen in this screenshot of the reformatted template:
![Code_UdpRXuWNxy](https://user-images.githubusercontent.com/1408662/190105811-430226c3-290e-4a2e-93e9-9fb35a030816.png)

2022-09-14 21:32 UTC, takinbo approved these changes

2022-09-14 21:32 UTC, merged