Image delete functionality
nditech/dev-elections pull request #905
Opened 2022-09-19 10:57 UTC by dodumosu

this PR implements nditech/apollo-issues#182 and adds front end functionality to delete images.

2022-09-21 11:03 UTC, takinbo requested changes

2022-09-21 11:03 UTC, takinbo commented on apollo/frontend/templates/frontend/macros/submission_field_macros.html
> +{% endif %}
I would have thought the permission only affects the delete button but here it also prevents uploading a replacement. Why?

2022-09-21 11:07 UTC, dodumosu commented
The linked issue specifically mentioned not allowing uploads as well.

On Wed, 21 Sep 2022, 12:03 Tim Akinbo, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In apollo/frontend/templates/frontend/macros/submission_field_macros.html
> <https://github.com/nditech/apollo/pull/905#discussion_r975978054>:
>
> > +{% if perms.delete_images.can() %}
> +<label class="btn btn-danger mx-2" data-delete-label="{{ form_field.short_name }}"><span role="button" tabindex="1"><i class="fa fa-trash"></i></span></label>
>  <label class="btn btn-secondary mx-2" style="cursor: pointer;" data-context="select_button">
>    <span role="button" tabindex="0"><i class="fas fa-file-upload"></i></span>
>    <input type="file" name="{{ form_field.name }}" id="{{ form_field.id }}" data-context="hidden_file" accept=".jpg,.png,image/jpeg,image/png" hidden />
>  </label>
> +{% endif %}
>
> I would have thought the permission only affects the delete button but
> here it also prevents uploading a replacement. Why?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nditech/apollo/pull/905#pullrequestreview-1114681847>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKX5FROCJ4V6H5MYXMVGWLV7LTP5ANCNFSM6AAAAAAQP7U74M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-01 21:03 UTC, takinbo requested changes
A few changes requested: 

1. The user should be able to delete an image upload that has not been saved. This means that it would not make a backend request to delete the image since it hasn't been uploaded yet.
2. Add the `cursor: pointer` style option when the delete button can be interacted with. Note that simply disabling the button doesn't prevent the pointer from looking the way it's been specified with the style.

2022-10-04 18:20 UTC, takinbo commented
![Screenshot from 2022-10-04 18-19-34](https://user-images.githubusercontent.com/41004/193895656-a71f4ddf-0934-4a83-b579-8905b52915e5.png)

Could you get rid of the notification displayed on the screen after deleting an image.

2022-10-05 16:14 UTC, takinbo requested changes

2022-10-05 16:14 UTC, takinbo commented on apollo/frontend/templates/frontend/submission_edit.html
> +      document.querySelector(galleryItemSelector).remove();
This assumes that the request will always succeed. Shouldn't it only do this if the response was OK?

2022-10-05 18:04 UTC, takinbo requested changes
Weird behavior: When an image is selected for the first time, the delete button is enabled (correctly) but when another image is selected (without clicking the delete button), it get disabled which shouldn't be.

2022-10-05 19:58 UTC, dodumosu commented
> Weird behavior: When an image is selected for the first time, the delete button is enabled (correctly) but when another image is selected (without clicking the delete button), it get disabled which shouldn't be.

this should be fixed

2022-10-05 20:28 UTC, takinbo approved these changes

2022-10-05 20:28 UTC, merged