Improved image pane
nditech/dev-elections pull request #919
Opened 2022-11-11 17:52 UTC by dodumosu

Implements the changes requested on nditech/apollo-issues#180

2022-11-30 08:26 UTC, dodumosu commented
@takinbo would we still need the image gallery with this feature? it's been left in for now, though

2022-12-06 05:04 UTC, takinbo commented
Answer is yes we would still need the image gallery. Any progress on the issue regarding the icon display on Chromium?

2022-12-06 06:18 UTC, dodumosu commented
> Answer is yes we would still need the image gallery. Any progress on the issue regarding the icon display on Chromium?

none. it happens in Google Chrome as well.

2023-01-04 13:27 UTC, takinbo commented
@dodumosu Before I merge this, could you also change the behaviour of the thumbnails so that when they are clicked on, they load the image in the split view rather than in the Lightbox as it currently does?

2023-01-04 18:05 UTC, dodumosu commented
> @dodumosu Before I merge this, could you also change the behaviour of the thumbnails so that when they are clicked on, they load the image in the split view rather than in the Lightbox as it currently does?

done. waiting for feedback

2023-01-08 19:34 UTC, takinbo requested changes

2023-01-08 19:34 UTC, takinbo commented on apollo/frontend/templates/frontend/submission_edit.html
> +            <a data-lightbox="images" data-title="{{ item['tag'] }} &middot; {{ item['description'] }}">
Could you also remove the extraneous references to Lightbox in the markup?

2023-01-09 07:42 UTC, takinbo approved these changes
LGTM

2023-01-09 07:45 UTC, merged