fix: update message generation to handle incidents and surveys
nditech/dev-elections pull request #942
Opened 2023-02-26 17:51 UTC by dodumosu

this PR adds support for generating correct SMS messages for incident and survey forms

2023-04-03 09:46 UTC, takinbo requested changes

2023-04-03 09:46 UTC, takinbo commented on apollo/odk/utils.py
> +
Shouldn't there be a valid serial number? If `serial=None` shouldn't this check that it is non-null and handle such a case? Or maybe there shouldn't be a default value and there should be a constraint for surveys?

2023-04-03 14:29 UTC, dodumosu commented on apollo/odk/utils.py
> +
there won't always be a serial number, for example, if the form is a checklist. my reasoning was that this way reduces the number of changes necessary to the calling code for the function. however, i will add an extra check to only add the serial to the logged message when the serial is present and it is a survey form

2023-04-03 14:43 UTC, takinbo commented on apollo/odk/utils.py
> +
Agreed. You should add the default value back so as to allow the method to be used for regular checklists.

2023-04-05 06:25 UTC, dodumosu commented
this should resolve nditech/apollo-issues#203

2023-11-06 14:44 UTC, takinbo requested changes

2023-11-06 14:44 UTC, takinbo commented on apollo/odk/utils.py
> +        message_body += '!'
AFAICT, we've seen moved from requiring a "I" in critical incident messages. No?

2023-11-06 15:45 UTC, dodumosu commented on apollo/odk/utils.py
> +        message_body += '!'
we still use it in the messaging code, so i thought it safer to leave it in (because of the possibility of later ingesting exported messages)

2023-11-07 17:00 UTC, takinbo approved these changes
utACK

2023-11-07 17:00 UTC, merged