adds support for searching in integer and select fields
nditech/dev-elections pull request #948
Opened 2023-08-22 08:37 UTC by dodumosu

this pull request adds support for querying submissions by field value (currently, **only integer and select fields are supported**). some screenshots to illustrate:

![chrome_xSBqveIvTP](https://github.com/nditech/apollo/assets/1408662/7b37372d-a0e7-421f-b7f1-ec2b5be8c93f)
![3P1RWCw3j5](https://github.com/nditech/apollo/assets/1408662/0b63a492-9e8d-42c3-8922-a93e524c1c09)
![QGBIYqaCQh](https://github.com/nditech/apollo/assets/1408662/acb12b31-0d1a-4ca3-a2ee-c4ca9eadcc3f)
![iwHQ1U4TBI](https://github.com/nditech/apollo/assets/1408662/97d60439-c34d-4935-befe-6091fd1831cd)

it supports multiple terms, but all terms are conjoined (that is, using `AND`).

2023-08-22 08:38 UTC, dodumosu commented
this is both a PR and a request for feedback, especially as regards the UI and UX

2023-09-11 15:14 UTC, dodumosu commented
![chrome_WcsdSQ02Uw](https://github.com/nditech/apollo/assets/1408662/862cfe02-7cf1-4549-bc08-02db54532f94)

![chrome_cwK0UyjY4Z](https://github.com/nditech/apollo/assets/1408662/8cacf6e7-435d-4b44-b7f9-4825d1c1fa7c)

added links from data summary

2023-11-07 16:59 UTC, takinbo requested changes

2023-11-07 16:59 UTC, takinbo commented on apollo/submissions/qa/query_builder.py
> +            exponent **= i
What's the difference between `func.pow` and `**=`

2023-11-07 17:20 UTC, dodumosu commented on apollo/submissions/qa/query_builder.py
> +            exponent **= i
ah. okay, that's in the base class. `func.pow()` is only useful when we're generating a query. it won't work in the event that we're in the InlineQA subclass

2023-12-19 16:00 UTC, takinbo requested changes
Is there a better way to represent the value of the Fields Value textbox in the URL?

Currently, it looks like this: /submissions/165?participant_id=&sample=&location_group=&values=%5B%7B"value"%3A"AD%3D1"%7D%5D

which is not elegant. I will also send you a diff to apply to the tagify css to make the field more uniform with the rest of the controls.

2023-12-19 16:13 UTC, takinbo commented
@dodumosu also use title case for the value "Field values". It should be "Field Values"

2023-12-20 11:58 UTC, takinbo commented
Resolves nditech/apollo-issues#185

2024-01-23 17:16 UTC, dodumosu commented
closing in favour of a new implementation which will be pushed soon.

2024-01-23 17:16 UTC, closed without merging

2024-01-23 18:06 UTC, dodumosu commented
replaced by #960