allow admins export results tables
nditech/dev-elections pull request #952
Opened 2023-09-18 10:01 UTC by dodumosu

2023-09-18 10:04 UTC, dodumosu commented
see nditech/apollo-issues#219

2023-12-18 21:45 UTC, takinbo requested changes
I've relocated the export button to a different location but couldn't modify your branch so I've made a patch file you can apply. You'll find the patch file in your email.

2023-12-19 06:24 UTC, dodumosu commented
> I've relocated the export button to a different location but couldn't modify your branch so I've made a patch file you can apply. You'll find the patch file in your email.

applied

2023-12-19 14:47 UTC, takinbo approved these changes

2023-12-19 14:47 UTC, merged